# In this notebook, we are going to cover some of the most fundamental concepts of tensor using Tensorflow

1. Intro to tensors
2. Getting information from tensors
3. Manipulating tensors
4. Tensors and numpy
5. Using tf.function

# Introduction to Tensors

In [2]:
%pip install tensorflow

^C
Note: you may need to restart the kernel to use updated packages.


In [1]:
#Import Tensorflow

import tensorflow as tf
import numpy as np

print(tf.__version__)

2.11.0


In [5]:
# Create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
# Check the number of dimension of tensor

scalar.ndim

0

In [7]:
# Create a vector

vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [8]:
# Check the dimension of our vector
vector.ndim

1

In [9]:
# Create a matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [10]:
matrix.ndim

2

In [11]:
# create a another matrix
another_matrix = tf.constant([[10., 7.],
                              [7., 10.],
                              [8., 9.]], dtype=tf.float16) # specifty the data type 

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [12]:
another_matrix.ndim

2

In [13]:
# Lets create a tensor
tensor = tf.constant([[[3, 4, 5],
                       [1, 2, 3]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 3,  4,  5],
        [ 1,  2,  3]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [14]:
tensor.ndim

3

# What we've created so far:
# 1. Scalar : a single number
# 2. Vector : a number with direction
# 3. Matrix: a 2-dimensional array of number
# 4. Tensor: a n-dimensional array of number

Creating tensor with Variable

tf.Variable(
    initial_value=None,
    trainable=None,
    validate_shape=True,
    caching_device=None,
    name=None,
    variable_def=None,
    dtype=None,
    import_scope=None,
    constraint=None,
    synchronization=tf.VariableSynchronization.AUTO,
    aggregation=tf.compat.v1.VariableAggregation.NONE,
    shape=None,
    experimental_enable_variable_lifting=True
)

In [15]:
changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [16]:
# Lets try change one of the elements in out changeable tensor
changable_tensor[0] = 7

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# try .assign()
changable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [17]:
# try changeing unchangable tensor
unchangable_tensor[0].assign(7)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
# Creating random tensors

random_1 = tf.random.Generator.from_seed(7) # set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))

random_2 = tf.random.Generator.from_seed(7)
random_2 = tf.random.normal(shape=(3, 2))

# are the equal?
random_1, random_2, random_1 == random_2


(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 1.1477073 ,  0.23339772],
        [ 0.22645174,  0.06458445],
        [-1.49607   , -0.45280266]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

# Suffle the order of elements in tensor


In [ ]:
not_shuffled = tf.constant([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9],
                            [10, 11, 12],
                            [13, 14, 15]])

# not_shuffled = tf.constant([5, 6, 7])

tf.random.set_seed(43) # seting global seed t0 43
tf.random.shuffle(not_shuffled, seed=43) # seting operational seed to 43

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [13, 14, 15],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [10, 11, 12]], dtype=int32)>

# It looks life if we want our shuffled tensors to be in the same order, we've got to use the global level random seed as well as the operation level random seeed:
# > if both global and the operation seed are set: Both seed are used in conjuction to determine the random sequence

Other ways to create tensor

In [18]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [19]:
# Create a tensor of all zeros
tf.zeros([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [20]:
# You can also turn Numpy arrays into tensors
# The main diff betn Numpy arrays and Tensorflow tensors is that tensors can be run on GPU computing

# Getting infromation from tensors

* Shape
* Rank
* Axis or dim
* Size

In [21]:
import tensorflow as tf
#create a rank 4 tensor (4 dimension)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [22]:
rank_4_tensor[0][0][0]

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [23]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [24]:
#get various attributes of our tensor

print("Datatype of every elemnet", rank_4_tensor.dtype)
print("number of dimensions (rank) : ", rank_4_tensor.ndim)
print("Shape of tensor : ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print('Total number of elements in our tensor', tf.size(rank_4_tensor).numpy())

Datatype of every elemnet <dtype: 'float32'>
number of dimensions (rank) :  4
Shape of tensor :  (2, 3, 4, 5)
Elements along the 0 axis:  2
Total number of elements in our tensor 120


#Indexing Tensors

Tensors can be indexed just like Python lists.

In [25]:
print(rank_4_tensor[:2, :2, :2, :2])

tf.Tensor(
[[[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]]]], shape=(2, 2, 2, 2), dtype=float32)


In [30]:
# Create a rank 2 tensor (2 dim)
rank_2_tensor = tf.constant([[1, 2],
                            [3, 4]])
rank_2_tensor.ndim

2

In [40]:
# Get the last item of each of row of our rank 2 tensor 
rank_2_tensor[:, -1].numpy()

array([2, 4])

In [42]:
#Add in extra dimension to our rank 2 tensor
rank2_to_3 = rank_2_tensor[..., tf.newaxis]
rank2_to_3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]])>

In [43]:
# Alternative to tf.newaxis 
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]])>

In [50]:
# Expand 0 axis
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]])>

In [88]:
# Manipulating tensors (tensor operation)

Manipulating tensors (tensor operation)

Basic operation

In [52]:
tensor = tf.constant([[10, 7], 
                    [3, 4]])

tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [53]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [54]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]])>

In [55]:
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]])>

In [60]:
# We can use the tensorflow builtin function to 
tf.math.multiply(tensor, 5), tf.math.subtract(tensor, 5), tf.math.add(tensor, -5)

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[50, 35],
        [15, 20]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 5,  2],
        [-2, -1]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 5,  2],
        [-2, -1]])>)

In [58]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

Matrix Multiplication

In machine learning matrix multiplication is one of the most common tensor operation

Rule1: The inner dimension must match
Rule2: The resulting has a shope of the outer dimension

In [61]:
# Matrix multiplication in tensorflow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]])>

In [63]:
# Matrix multiplication with python operator '@'
tensor * tensor, tensor @ tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[100,  49],
        [  9,  16]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[121,  98],
        [ 42,  37]])>)

In [64]:
tensor.shape

TensorShape([2, 2])

In [72]:
#Crate a tensor of [3, 2] tesnor

x = tf.constant([[1, 2],[3, 4], [5, 6]])
x.shape
y = tf.constant([[7, 8, 9], [10, 11, 12]])
x.shape, y.shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [73]:
y @ x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 76, 100],
       [103, 136]])>

In [74]:
x @ y

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [77]:
x = tf.constant([[1, 2], [3, 4], [5, 6]])
y = tf.constant([[7, 8], [9, 10], [11, 12]])
x.shape, y.shape

(TensorShape([3, 2]), TensorShape([3, 2]))

In [79]:
#Lets change the shape of y
tf.reshape(y, shape=[2, 3])

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [80]:
# Try to matrix multiply x by reshaped y
x @ tf.reshape(y, shape=[2, 3])


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [81]:
tf.matmul(x, tf.reshape(y, shape=[2, 3]))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [84]:
tf.matmul(tf.reshape(x, shape=[2, 3]), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [86]:
# Can do the same with transpose
x, tf.transpose(x), tf.reshape(x, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>)

In [87]:
# Try matrix multiplication with transpose
tf.matmul(tf.transpose(x), y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [91]:
# The dot products

# Matrix Multiplication is also referrd to as the dot product.

# You can perform matrix multiplication using: 
    # tf.matmul()
    # tftf.tensordot()
    # @

In [92]:
x, y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [99]:
# Perform the dot product on X and Y (requires x and y)
tf.tensordot(tf.transpose(x), y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [100]:
tf.tensordot(tf.transpose(y), x, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89, 116],
       [ 98, 128]])>

In [101]:
tf.tensordot(x, tf.transpose(y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [103]:
tf.matmul(x, tf.reshape(y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [105]:
# Check the values of y, reshape y and transposed y
print("Normal y: ")
print(y, "\n")

print("y reshaped to (2, 3): ")
print(tf.reshape(y, shape=(2, 3)))
print("\n")

print("Transposing y")
print(tf.transpose(y))

Normal y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

y reshaped to (2, 3): 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)


Transposing y
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to get satifgy the matrix multiplication rule

In [109]:
# Changing the data type of a tesnor


# Creating anew tensor with default datatype (float32)
B = tf.constant([1.2, 3.4])
B

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.2, 3.4], dtype=float32)>

In [110]:
C = tf.constant([1, 2])
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [111]:
# Change from float32 to float16 (reduced precison)

B = tf.cast(B, dtype=tf.float16)
B.dtype


tf.float16

In [113]:
# Change from int32 to int16

C = tf.cast(C, dtype=tf.int16)
C.dtype

tf.int16

In [115]:
# Change from float to int

D = tf.cast(B, dtype=tf.int16)
D.dtype, D

(tf.int16,
 <tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 3], dtype=int16)>)

In [116]:
D = tf.cast(D, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 3.], dtype=float16)>,
 tf.float16)

Aggregating Tensors

Aggregating tesnors = condensing them from multiple values down to a smaller amount of values

In [119]:
# Geting the absolute values

D = tf.constant([-7, -10])

D, tf.abs(D)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>)

Lets go through the following forms of aggregation:
* Get the minimun
* Get the maximum 
* Get the mean of a tensor
* Get the sum of the tesnor

In [125]:
tf.minimum(x, y), tf.maximum(x, y)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [127]:
tf.reduce_mean(x), x

(<tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>)

In [128]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [136]:
# Crating a random tesnor with random values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([28, 32, 72, 25, 94,  3, 63, 27, 15, 86, 17, 57, 26, 31, 95, 54, 69,
        7, 66, 41, 36, 94,  7, 12, 51, 47, 54, 77, 16, 41, 64, 35, 87, 35,
       88, 18, 67, 55, 52, 99, 71,  2, 52, 17, 72, 29, 53, 99, 32, 84])>

In [145]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [146]:
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [147]:
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [148]:
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=49>

In [149]:
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2454>

In [153]:
E = tf.cast(E, tf.float16)
tf.math.reduce_variance(E)

<tf.Tensor: shape=(), dtype=float16, numpy=782.0>

In [156]:
tf.math.reduce_std(E)

<tf.Tensor: shape=(), dtype=float16, numpy=27.97>

Find the positional maximum and minimun

In [164]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [168]:
tf.math.argmax(F), np.argmax(F)

(<tf.Tensor: shape=(), dtype=int64, numpy=42>, 42)

In [170]:
F[tf.argmax(F)], tf.reduce_max(F)

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>)

In [169]:
tf.math.argmin(F), np.argmin(F)

(<tf.Tensor: shape=(), dtype=int64, numpy=16>, 16)

In [171]:
F[16]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

Squeezing a tensor (removing all single dimensions)

In [173]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G


<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [174]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [176]:
G_squeezed = tf.squeeze(G)
G_squeezed.shape, G_squeezed

(TensorShape([50]),
 <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>)

One Hot encoding

* form of numerical encoding

In [184]:
# Crate a list of indices
some_list = [0, 1, 1, 3]

# One Hot encode our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [185]:
# Specify custom values
tf.one_hot(some_list, depth=4, on_value="yo I love DL", off_value="I love running")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love DL', b'I love running', b'I love running',
        b'I love running'],
       [b'I love running', b'yo I love DL', b'I love running',
        b'I love running'],
       [b'I love running', b'yo I love DL', b'I love running',
        b'I love running'],
       [b'I love running', b'I love running', b'I love running',
        b'yo I love DL']], dtype=object)>

In [186]:
# Squaring, log, square root
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [187]:
#Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [190]:
# Find the square root
tf.sqrt(tf.cast(H, tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [194]:
tf.math.log(tf.cast(H, tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

Numpy and tensorflow

tenserflow interacts beautifully with Numpy arrays


In [3]:
J = tf.constant(np.array([2, 7, 4]))
J

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 7, 4])>